{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-coroutines-core/1.5.2-native-mt/kotlinx-coroutines-core-1.5.2-native-mt.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-core",
    "version": "1.5.2-native-mt",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "canynfwr5rfqplg4dbabyixeqa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.5.2-native-mt.jar",
          "url": "kotlinx-coroutines-core-jvm-1.5.2-native-mt.jar",
          "size": 1494355,
          "sha512": "4256769b65eb4378ad84d2f8078797824785b0b8dd4cc92c7da11f509f22ae5a44aeb6cf368832c8d9c5aa42e83bd150be78742a4f83afa8ef1725e8dd42499e",
          "sha256": "db754be65cd22e18c8861a141cc35cedc3b659292eacb7f9d2c78a5386795dec",
          "sha1": "26a9506d10d933615533c703483cec0a5c13a9f3",
          "md5": "e540563c8de606baa5b58534d04dac00"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-core-jvm-1.5.2-native-mt.jar",
          "url": "kotlinx-coroutines-core-jvm-1.5.2-native-mt.jar",
          "size": 1494355,
          "sha512": "4256769b65eb4378ad84d2f8078797824785b0b8dd4cc92c7da11f509f22ae5a44aeb6cf368832c8d9c5aa42e83bd150be78742a4f83afa8ef1725e8dd42499e",
          "sha256": "db754be65cd22e18c8861a141cc35cedc3b659292eacb7f9d2c78a5386795dec",
          "sha1": "26a9506d10d933615533c703483cec0a5c13a9f3",
          "md5": "e540563c8de606baa5b58534d04dac00"
        }
      ]
    }
  ]
}
