{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "koin-android",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "o5pwrx7pejfpnj3jvzvi4mqoim"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-android-3.1.2.aar",
          "url": "koin-android-3.1.2.aar",
          "size": 119744,
          "sha512": "e09fc20354e3309e62bfa4c65ecea28d49b439a20ceb3900de50faf1dacf662b08c26cfb069386c7b1f6cff3d32f0118c67bff58a93a8aba07454b8c1339a4c9",
          "sha256": "10be5a5203ae5b06f5f5bf99308d72ca468841005b748891c3ac24ddf6d2ca38",
          "sha1": "24bbcb65ddd73462aefb1084ae8714a2d7e014de",
          "md5": "f81a1d7f73ea5136d5bd4377b45c6b22"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.3.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "lifecycle-service"
            },
            {
              "group": "*",
              "module": "lifecycle-process"
            },
            {
              "group": "androidx.legacy",
              "module": "*"
            },
            {
              "group": "*",
              "module": "lifecycle-livedata"
            },
            {
              "group": "*",
              "module": "runtime"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "koin-android-3.1.2.aar",
          "url": "koin-android-3.1.2.aar",
          "size": 119744,
          "sha512": "e09fc20354e3309e62bfa4c65ecea28d49b439a20ceb3900de50faf1dacf662b08c26cfb069386c7b1f6cff3d32f0118c67bff58a93a8aba07454b8c1339a4c9",
          "sha256": "10be5a5203ae5b06f5f5bf99308d72ca468841005b748891c3ac24ddf6d2ca38",
          "sha1": "24bbcb65ddd73462aefb1084ae8714a2d7e014de",
          "md5": "f81a1d7f73ea5136d5bd4377b45c6b22"
        }
      ]
    }
  ]
}
