{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.0.0-alpha.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "5jv6thsazzdcnjmfhf6a3x3lwi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-5.0.0-alpha.2.jar",
          "url": "okhttp-5.0.0-alpha.2.jar",
          "size": 806835,
          "sha512": "13939a038db8d9a510bd40099829a32dc30df191cbe03288ac85297c34eead432532c9b1fe590c7ff67b3cb348abfd543d9fe0444af5effdb81495e7d8339acd",
          "sha256": "ea5ccaddc0e61dd5927a9f603b12c7541f2dca4b3d57660e98e69c6800e1f5ff",
          "sha1": "bf7bed2b2469e05290e258813396114ef080f574",
          "md5": "7de2e3634d6d08ebc70708800f344b8d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-5.0.0-alpha.2.jar",
          "url": "okhttp-5.0.0-alpha.2.jar",
          "size": 806835,
          "sha512": "13939a038db8d9a510bd40099829a32dc30df191cbe03288ac85297c34eead432532c9b1fe590c7ff67b3cb348abfd543d9fe0444af5effdb81495e7d8339acd",
          "sha256": "ea5ccaddc0e61dd5927a9f603b12c7541f2dca4b3d57660e98e69c6800e1f5ff",
          "sha1": "bf7bed2b2469e05290e258813396114ef080f574",
          "md5": "7de2e3634d6d08ebc70708800f344b8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-5.0.0-alpha.2-javadoc.jar",
          "url": "okhttp-5.0.0-alpha.2-javadoc.jar",
          "size": 261,
          "sha512": "c19ee3ee7d48252248e4223a85ea8a1837d4acb943e46c452b33d81d7c2b1addf285bf9b579a90906f0e4f1fffcf79ff1ff5374485032840f08841880ff0e0b1",
          "sha256": "024950eac7230ab0d3b9121feb0c3dcea875542f05d91b0860d53d57cee9785c",
          "sha1": "eff136ec112345cba482d2e4fb6491ba3d2bcc37",
          "md5": "0a3f7834a42404071c8ca18a6b35381e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-5.0.0-alpha.2-sources.jar",
          "url": "okhttp-5.0.0-alpha.2-sources.jar",
          "size": 367152,
          "sha512": "0d061c1af79c3690938d5d152c1236befa60c3cc660f825cfab62dda3d618c16af15bff30372fc8dd940e05b3df451d93feaf6f6798f47ef2d21bf2b04144aa1",
          "sha256": "cce1bb5e23001c18aeead2aa4db905788caa0f3caacba7e713f8afacde08e3cb",
          "sha1": "c5d27b96fac9a64d3bf79d84f01af4c6d8e76de4",
          "md5": "47851bd7141a0edaa12ac94cb540d0b9"
        }
      ]
    }
  ]
}
