{
  "formatVersion": "1.1",
  "component": {
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "m75ohggcyjbl5dwv5zyxsqwos4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-metadata-3.1.2-all.jar",
          "url": "koin-core-3.1.2-all.jar",
          "size": 37431,
          "sha512": "0c14f40d7eb10b8324da41533a9f681f2eccc594f8f5388b7f7e314f674cfee6600eaafc7bf8b523be579c6316ac29a8cd32b1b089264fbb8c8f391e03e03458",
          "sha256": "0509fcaf3d3f0cc179cddc7ee4de261c0a9e23ed68317832c4b7165b7e78d75c",
          "sha1": "f47c02d7c995b34099ec3838f6842fffd38816a4",
          "md5": "3dd8f6d35f8ee188d58f85b99a375149"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-3.1.2.jar",
          "url": "koin-core-3.1.2.jar",
          "size": 32395,
          "sha512": "715074a3b24955ead1246e248ef2a03faccda4b30337b73a9f3b548b45a447110a0af2a60564f0a5b9d80d22255da31d20335a79a2aa62ef64f1bdb2f572f9b3",
          "sha256": "b7f9001665c1f97969071c4554e7011bf2e2e06f2bfc35363795853bfd1ac508",
          "sha1": "85b4c7a17b649e23f8c2226ed749c2d08f3f3eaf",
          "md5": "ebf38a3cd7387109d653376293bd2fe6"
        }
      ]
    },
    {
      "name": "iosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm32/3.1.2/koin-core-iosarm32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm32",
        "version": "3.1.2"
      }
    },
    {
      "name": "iosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm32/3.1.2/koin-core-iosarm32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm32",
        "version": "3.1.2"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/3.1.2/koin-core-iosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosarm64/3.1.2/koin-core-iosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/3.1.2/koin-core-iosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-iosx64/3.1.2/koin-core-iosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-iosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.1.2/koin-core-js-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.1.2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.1.2/koin-core-js-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.1.2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.1.2/koin-core-js-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.1.2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../koin-core-js/3.1.2/koin-core-js-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-js",
        "version": "3.1.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/3.1.2/koin-core-jvm-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "3.1.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../koin-core-jvm/3.1.2/koin-core-jvm-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-jvm",
        "version": "3.1.2"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxarm32hfp/3.1.2/koin-core-linuxarm32hfp-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxarm32hfp",
        "version": "3.1.2"
      }
    },
    {
      "name": "linuxMips32ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxmips32/3.1.2/koin-core-linuxmips32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxmips32",
        "version": "3.1.2"
      }
    },
    {
      "name": "linuxMips32MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "linux_mips32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxmips32/3.1.2/koin-core-linuxmips32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxmips32",
        "version": "3.1.2"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-linuxx64/3.1.2/koin-core-linuxx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-linuxx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/3.1.2/koin-core-macosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-macosx64/3.1.2/koin-core-macosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-macosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-mingwx64/3.1.2/koin-core-mingwx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-mingwx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "mingwX64MetadataElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-mingwx64/3.1.2/koin-core-mingwx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-mingwx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/3.1.2/koin-core-tvosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosarm64/3.1.2/koin-core-tvosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/3.1.2/koin-core-tvosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-tvosx64/3.1.2/koin-core-tvosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-tvosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/3.1.2/koin-core-watchosarm32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm32/3.1.2/koin-core-watchosarm32-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm32",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/3.1.2/koin-core-watchosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosarm64/3.1.2/koin-core-watchosarm64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosarm64",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/3.1.2/koin-core-watchosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx64/3.1.2/koin-core-watchosx64-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx64",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx86/3.1.2/koin-core-watchosx86-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx86",
        "version": "3.1.2"
      }
    },
    {
      "name": "watchosX86MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../koin-core-watchosx86/3.1.2/koin-core-watchosx86-3.1.2.module",
        "group": "io.insert-koin",
        "module": "koin-core-watchosx86",
        "version": "3.1.2"
      }
    }
  ]
}
