{
  "formatVersion": "1.1",
  "component": {
    "url": "../../koin-core/3.1.2/koin-core-3.1.2.module",
    "group": "io.insert-koin",
    "module": "koin-core",
    "version": "3.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "m75ohggcyjbl5dwv5zyxsqwos4"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-3.1.2.jar",
          "url": "koin-core-jvm-3.1.2.jar",
          "size": 175283,
          "sha512": "e522d71893c13eb0447531cda1f77c3e22eb2dbb7562d339d47470ad2234df25b1396e4f47d82bdc10909741cb5e2a4355a1f4433e8a194facf671412e36e0af",
          "sha256": "cfba5a3193f6f17a59a9eb819b392b5ef417f84faf3d16810f2a83e801c0dc42",
          "sha1": "426d272f292cfdc37b0c4b0d7dd3235ca96b0625",
          "md5": "f3177ade5daf53dda262548336fc2389"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.10"
          }
        }
      ],
      "files": [
        {
          "name": "koin-core-jvm-3.1.2.jar",
          "url": "koin-core-jvm-3.1.2.jar",
          "size": 175283,
          "sha512": "e522d71893c13eb0447531cda1f77c3e22eb2dbb7562d339d47470ad2234df25b1396e4f47d82bdc10909741cb5e2a4355a1f4433e8a194facf671412e36e0af",
          "sha256": "cfba5a3193f6f17a59a9eb819b392b5ef417f84faf3d16810f2a83e801c0dc42",
          "sha1": "426d272f292cfdc37b0c4b0d7dd3235ca96b0625",
          "md5": "f3177ade5daf53dda262548336fc2389"
        }
      ]
    }
  ]
}
