{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7276851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.3.0.aar",
          "url": "room-ktx-2.3.0.aar",
          "size": 33365,
          "sha512": "a8328b2ac8a2ca63208f565f45ed3822b1ecc83b856ea146deebeba146987e8294ff59b0cc03100375ede718f0d26a87e81ef61cbe5387b1bb9f1e5da04d5985",
          "sha256": "a671c2d28779546a7fa195b941bd441a1b594988c4c8a70080017f71095d7af6",
          "sha1": "aed50d28edbaaa003aecb75553c848ae2d0dc63a",
          "md5": "38da84cecabfe149fa38dc0be4df1258"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.3.0.aar",
          "url": "room-ktx-2.3.0.aar",
          "size": 33365,
          "sha512": "a8328b2ac8a2ca63208f565f45ed3822b1ecc83b856ea146deebeba146987e8294ff59b0cc03100375ede718f0d26a87e81ef61cbe5387b1bb9f1e5da04d5985",
          "sha256": "a671c2d28779546a7fa195b941bd441a1b594988c4c8a70080017f71095d7af6",
          "sha1": "aed50d28edbaaa003aecb75553c848ae2d0dc63a",
          "md5": "38da84cecabfe149fa38dc0be4df1258"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-ktx-2.3.0-sources.jar",
          "url": "room-ktx-2.3.0-sources.jar",
          "size": 4813,
          "sha512": "5d69f2081e7f04c9608c9467a339dde9fc8b5f8f7abbab45122281076d85e83e78768e56479602bdcf3640074268075cee71e4eaedec8d952a61d520891b8500",
          "sha256": "8b3d575958bbb737db185c00836bf3964bad322e6e184414b0aea049b88a4a9a",
          "sha1": "f8b846b2835c246c1a1181674e9f44e6d6485913",
          "md5": "34d536f593c5453b2a6ca695b48bdd3e"
        }
      ]
    }
  ]
}
