{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7276851"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0.aar",
          "url": "room-runtime-2.3.0.aar",
          "size": 135504,
          "sha512": "6386cd8f7f7bcf59bd5b569ea6f95e121a9e7af773444a64eac5fc9430d28be9342722f7b9ea43664bf31bf807afa5ba00677b889af7c4fcfd4924921b7d37e9",
          "sha256": "3296970e92d85f098f26e776911da3bd9bb084acd37440bd1705fd163f4a93f9",
          "sha1": "58ae8ce5195194b5299b482787bf3c1591f6db13",
          "md5": "884278735ae8b87f0c72696a8ed17d27"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0.aar",
          "url": "room-runtime-2.3.0.aar",
          "size": 135504,
          "sha512": "6386cd8f7f7bcf59bd5b569ea6f95e121a9e7af773444a64eac5fc9430d28be9342722f7b9ea43664bf31bf807afa5ba00677b889af7c4fcfd4924921b7d37e9",
          "sha256": "3296970e92d85f098f26e776911da3bd9bb084acd37440bd1705fd163f4a93f9",
          "sha1": "58ae8ce5195194b5299b482787bf3c1591f6db13",
          "md5": "884278735ae8b87f0c72696a8ed17d27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.3.0-sources.jar",
          "url": "room-runtime-2.3.0-sources.jar",
          "size": 92316,
          "sha512": "1cf32c9f23e563449c0e9a0d8f2e21ace5c35beec72ee68d35fa66771463012b2bfbc66fec9cfa3ab1512772b4ee13c1f2ea00a11c8828e052d2b9f5933773ff",
          "sha256": "166e8c5dafc3dacdc689b0a42fbdbc60491e3e009dd03ceee6fc5bc1b32708d6",
          "sha1": "578ba82a8a4cbcdb53377bd57687ffbb2cb1924a",
          "md5": "a70fd00dc7c6c6fdfd832db645ee3955"
        }
      ]
    }
  ]
}
